# Generated by Django 6.0 on 2025-12-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_datetime',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='last_completed_at',
            new_name='scheduled_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_datetime',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_rule',
        ),
        migrations.RemoveField(
            model_name='task',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_rule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_type',
            field=models.CharField(choices=[('NONE', 'No Date'), ('SCHEDULED', 'Scheduled'), ('RANGE', 'Time Range'), ('RECURRING', 'Recurring')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
