# Generated by Django 6.0 on 2025-12-21 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('none', 'None'), ('value', 'Value'), ('sum', 'Sum'), ('threshold', 'Threshold')], max_length=10)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(default=0)),
                ('display_mode', models.CharField(choices=[('sum', 'Sum'), ('max', 'Max'), ('min', 'Min'), ('avg', 'Average')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='branches.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trackers.tracker')),
            ],
        ),
    ]
