# Generated by Django 6.0 on 2025-12-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='display_mode',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='user',
        ),
        migrations.AddField(
            model_name='tracker',
            name='tracker_type',
            field=models.CharField(choices=[('PLAIN', 'Plain'), ('INCREMENT', 'Incrementing'), ('DECREMENT', 'Decrementing')], default='PLAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='target_type',
            field=models.CharField(choices=[('NONE', 'No Target'), ('VALUE', 'Value'), ('SUM', 'Sum'), ('THRESHOLD', 'Threshold')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
